In [7]:
import pandas as pd
import numpy as np
import _general as GenFun
wirerunfilepath = 'InputData_none.csv'
_df = pd.read_csv(wirerunfilepath)
_fullwirerun = GenFun.WireRun_df(_df, 1)

In [8]:
_fullwirerun.head()

,PoleID,STA,Rail EL,MW Height,CW Height,PreSag,Deviation Angle,SpanLength
0,1,162297.0,0,24.0,20.00,0,0.000000,155.0
1,2,162452.0,0,23.5,19.25,0,-3.049614,160.0
2,3,162612.0,0,23.5,18.50,0,0.682093,133.0
3,4,162745.0,0,22.5,18.50,0,-0.618431,150.0
4,5,162895.0,0,22.5,18.50,0,-0.063662,173.0

In [12]:
val = _fullwirerun.copy()
val['Deviation Angle'].iloc[3] = np.NaN
val['Deviation Angle'] = abs(val['Deviation Angle'])

c:\temp\ipykernel_4124\4134744478.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  val['Deviation Angle'].iloc[3] = np.NaN
c:\temp\ipykernel_4124\4134744478.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val['Deviation Angle'].iloc[3] = np.NaN

In [13]:
val.head()

,PoleID,STA,Rail EL,MW Height,CW Height,PreSag,Deviation Angle,SpanLength
0,1,162297.0,0,24.0,20.00,0,0.000000,155.0
1,2,162452.0,0,23.5,19.25,0,3.049614,160.0
2,3,162612.0,0,23.5,18.50,0,0.682093,133.0
3,4,162745.0,0,22.5,18.50,0,NaN,150.0
4,5,162895.0,0,22.5,18.50,0,0.063662,173.0